### ISSUE TITLE
Extension not loading?

### ISSUE THREAD

**Issue by grzenkom** [GoogleCloudPlatform/jupyter-extensions#352]
I enabled the extension and I can see the "AI Platform Notebook Jobs" button. However, when I click it, an empty pane shows and nothing happens.

Are there any steps I need to perform before the extension is ready for use?

I tried to view the [end-user documentation linked in README](https://drive.google.com/file/d/1djM8fXBERSKkQ-avxM6Lv-kbfkjNucN_/view), but I have no access to this file.

**Comment by grzenkom** [comment]
That solved my issue!

All this time I was clicking the button on the left and did not notice the one at the top.

![image](https://user-images.githubusercontent.com/17741743/93486496-8b459500-f904-11ea-8c5e-7ccb9891b1ff.png)

Clicking "Schedule on GCP" (green arrow) guided me through the setup process and then the notebook was executed.

**Comment by prodonjs** [comment]
Thanks @grzenkom! I'm assuming then that you  had the AI Platform API enabled, but since you had never submitted a job you just saw the empty panel and there's no call-to-action there to initialize the extension.

Glad to see you got it working and that the initialization process was self-explanatory enough to get through it!
